### ISSUE TITLE
Dylib not loaded

### ISSUE THREAD

**Issue by arandomusernam** [m1stadev/Inferius#42]
I can't figure out what dependancy this is:
/opt/local/lib/libreadline.8.dylib
Any help would be appreciated
Thanks :)

**Comment by vadimszzz** [comment]
Full log please.

**Comment by vadimszzz** [comment]
If error occurs in my fork you must open issue in my fork.

**Comment by arandomusernam** [comment]
Ok Thanks. I'll open an issue over there. :)

**Comment by arandomusernam** [comment]
I can't open an issue over there, there is nowhere to open the issue. I think that this is missing some dependancies, I ran the command to install the dependencies, but some are still missing(I think, I don't know for sure.) Full log here:

./bundlegen -d iPhone9,4 -i 11.4.1
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/xdelta3/version.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import StrictVersion
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/ssl_.py:260: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  context = SSLContext(ssl_version or PROTOCOL_TLS)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py:407: DeprecationWarning: ssl.match_hostname() is deprecated
  match_hostname(cert, asserted_hostname)
Creating Firmware Bundle for iPhone9,4, iOS 11.4.1
[1] Grabbing decryption keys...
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/ssl_.py:260: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  context = SSLContext(ssl_version or PROTOCOL_TLS)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py:407: DeprecationWarning: ssl.match_hostname() is deprecated
  match_hostname(cert, asserted_hostname)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py:407: DeprecationWarning: ssl.match_hostname() is deprecated
  match_hostname(cert, asserted_hostname)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py:407: DeprecationWarning: ssl.match_hostname() is deprecated
  match_hostname(cert, asserted_hostname)
[2] Patching bootchain...
Traceback (most recent call last):
  File "/Users/tobinredekop/Downloads/Inferius-master 2/./bundlegen", line 412, in <module>
    main()
  File "/Users/tobinredekop/Downloads/Inferius-master 2/./bundlegen", line 296, in main
    delta.write(xdelta3.encode(original.read(), new_file.read()))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/xdelta3/main.py", line 89, in encode
    return _xdelta3.execute(new_value, original, flags, 0)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

**Comment by vadimszzz** [comment]
I don't see dylib problems, it was my bad that I didn't provide dylib for something. Looks like you already installed all dependencies, nice!

Now the problem is in xdelta3 library. It's outdated. To fix this problem please use only Python 3.9.0, not 3.10.

I already fixed this library but the author sent me fuck and he don't want to merge PR https://github.com/samuelcolvin/xdelta3-python/pull/14

**Comment by arandomusernam** [comment]
Thanks for the reply! I uninstalled Python 3.10 and installed Python 3.9.0, and I'm still getting the same error. Log:

Restoring custom IPSW
dyld: Library not loaded: /opt/local/lib/libreadline.8.dylib
  Referenced from: /Users/tobinredekop/Downloads/Inferius-master 2/./bin/irecovery
  Reason: image not found
[ERROR] Device in DFU mode not found. Exiting.

**Comment by arandomusernam** [comment]
There! Uninstalled Python 3.10, and tried again. This time it gave me another module not found error. Log:

./bundlegen -d iPhone9,4 -i 11.4.1
Traceback (most recent call last):
  File "/Users/tobinredekop/Downloads/Inferius-master 2/./bundlegen", line 4, in <module>
    from mwclient import Site
ModuleNotFoundError: No module named 'mwclient'

**Comment by vadimszzz** [comment]
`pip install -r requirements.txt`

**Comment by vadimszzz** [comment]
It looks like you never heard about Python before

**Comment by arandomusernam** [comment]
Sorry, I thought that I had installed the dependencies. Thanks for the fix :).

**Comment by arandomusernam** [comment]
It still says that I am missing libreadline.8.dylib.

**Comment by vadimszzz** [comment]
> It still says that I am missing libreadline.8.dylib.
> 
> EDIT: I did a bunch of research online about libreadline, and it looks like something that should only be required in Linux distros, such a Debian or Arch Linux. It sounds like macos should not need this...

I'll do a small script to properly install Inferius. Go to https://github.com/vadimszzz/Inferius and click „Watch“. It will be soon.

**Comment by arandomusernam** [comment]
Many thanks! I will go over there and watch it, best of luck with your coding!
